const NLBlotteryList = [
  {
    number: 1,
    title_en: "Suba Dawasak",
    title_si: "සුභ දවසක්",
    logo: require('../assets/subadawasak.png'),
    name_si: "Suba-dawasak",
    name: "suba-dawasak",
  },
  {
    number: 2,
    title_en: "Govisetha",
    title_si: "ගොවිසෙත",
    logo: require('../assets/govisetha.png'),
    name_si: "ගොවි-සෙත",
    name: "govisetha",
  },
  {
    number: 3,
    title_en: "Mahajana Sampatha",
    title_si: "මහජන සම්පත",
    logo: require('../assets/mahajana.png'),
    name_si: "මහජන-සම්පත",
    name: "mahajana-sampatha",
  },
  {
    number: 4,
    title_en: "Dhana Nidhanaya",
    title_si: "ධන නිධානය",
    logo: require('../assets/dhananidhanaya.png'),
    name_si: "ධන-නිධානය",
    name: "dhana-nidhanaya",
  },
  {
    number: 5,
    title_en: "Mega Power",
    title_si: "මෙගා පවර්",
    logo: require('../assets/megapower.png'),
    name_si: "මෙගා-පවර්",
    name: "mega-power",
  },
  // {
  //   number: 6,
  //   title_en: "Lucky 7",
  //   title_si: "ලකි 7",
  //   logo: require('../assets/lucky7.png'),
  //   name_si: "Lucky-7",
  //   name: "lucky-7",
  // },
  {
    number: 7,
    title_en: "Handahana",
    title_si: "හඳහන",
    logo: require('../assets/hadahana.png'),
    name_si: "හඳහන",
    name: "handahana",
  },
  {
    number: 8,
    title_en: "Ada Sampatha",
    title_si: "අද සම්පත",
    logo: require('../assets/adasampatha.png'),
    name_si: "අද-සම්පත",
    name: "ada-sampatha",
  },
  {
    number: 9,
    title_en: "NLB Jaya",
    title_si: "NLB ජය",
    logo: require('../assets/jaya.png'),
    name_si: "NLB-Jaya",
    name: "nlb-jaya",
  },
];

export default NLBlotteryList;
